name: Deploy to Jira

on:
  push:
    branches:
      - main  # Postavite odgovarajuću granu na koju želite da reagujete

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Use Node.js 16.x
            uses: actions/setup-node@v2
            with:
              node-version: 16.x
          - name: Checkout repository
            uses: actions/checkout@v2
          # Ostali koraci
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Send Deployment Data to Jira
              env:
                JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}  # Zamijenite sa URL-om vašeg Jira servera ili cloud instance
                JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}  # Postavka tajne iz GitHub Secrets
              run: |
                # Instalirajte Python zavisnosti za HTTP zahtev
                pip install requests

                # Definišite informacije o deploymentu
                DEPLOYMENT_VERSION="1.0.0"
                DEPLOYMENT_DESCRIPTION="Deployment opis"
                DEPLOYMENT_ENVIRONMENT="Production"

                # Kreirajte JSON payload sa informacijama o deploymentu
                JSON_PAYLOAD="{\"version\":\"${DEPLOYMENT_VERSION}\",\"description\":\"${DEPLOYMENT_DESCRIPTION}\",\"environment\":\"${DEPLOYMENT_ENVIRONMENT}\"}"

                # Pošaljite POST zahtev ka Jira REST API za kreiranje deployment događaja
                curl -X POST -H "Content-Type: application/json" -H "Authorization: Basic ${JIRA_API_TOKEN}" -d "${JSON_PAYLOAD}" "${JIRA_BASE_URL}/rest/deployments/2.0/deployments"